
    - name: Add vagrant user to docker group
      user: name=vagrant groups=docker append=yes
      sudo: yes
      tags:
      - qr
      - development
      - vagrant

    - name: Copy upstart script for docker services
      copy: src=docker-services.conf dest=/etc/init/ mode=0644
      notify:
      - Restart docker-services
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant
